apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.clusterName }}-{{ .Values.nodeGroup }}
  labels:
    app: {{ .Values.clusterName }}
    component: {{ .Values.nodeGroup }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Values.clusterName }}-{{ .Values.nodeGroup }}-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.clusterName }}
      component: {{ .Values.nodeGroup }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Values.clusterName }}
        component: {{ .Values.nodeGroup }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.sysctlInitContainer.enabled }}
      initContainers:
      - name: configure-sysctl
        image: busybox:1.35
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
          runAsUser: 0
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: elasticsearch
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range .Values.extraEnvs }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- end }}
          {{- if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: ES_JAVA_OPTS
          value: {{ .Values.esJavaOpts | quote }}
        - name: node.roles
          value: {{ .Values.roles | join "," | quote }}
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        {{- if .Values.esConfig }}
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        {{- end }}
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      {{- if .Values.esConfig }}
      - name: config
        configMap:
          name: {{ .Values.clusterName }}-config
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
